### ISSUE TITLE
start migration from command line

### ISSUE THREAD

**Issue by bh-ref** [ubertheme/module-ubdatamigration#1]
Hi, first of all thank you very much for creating this tool.

I work on shop which has 25000 simple products and 4400 grouped products. It takes several hours to finish the migration. Is it possible to add a functionality which starts the tool or a step like product migration from the command line using the php cli?

**Comment by quynhvv** [comment]
@bh-ref: 
Yes, this migration tool hasn't yet support command line use the php cli at this time. May be in the future.
Did you finished the data migration with this tool?
Regards,
quynhvv

**Comment by bh-ref** [comment]
I would definitely appreciate  the support of the cli in the future :)

Unfortunately, changing the php timeout is not an option in my environment. Therefore, I could not finish the data migration.

**Comment by bh-ref** [comment]
Luckily, changing the php timeout was an option. But unfortunately, the migration is not running through.

After filling in the information in step one, I usually get this error:
Error 500
include(Mage1WebsitePeer.php): failed to open stream: No such file or directory

![image](https://cloud.githubusercontent.com/assets/15156912/11751361/5b7b8970-a039-11e5-80ae-8f6a33a6b2a6.png)

but this hellps:
`php bin/magento indexer:reindex`
`php bin/magento cache:clean`

but after that, on step 5, it takes around 2 minutes...
![image](https://cloud.githubusercontent.com/assets/15156912/11751432/c8ec4c88-a039-11e5-8852-2dc5463a5499.png)

...and then this happens:
![image](https://cloud.githubusercontent.com/assets/15156912/11751482/0124d58e-a03a-11e5-9366-8258f3215b6f.png)

But there were somes products migrated.

`php bin/magento indexer:reindex`
`php bin/magento cache:clean`
does not help here.

The funny thing is, that if click on the link to the migration tool, it takes again some time, it even further migrates some more products, but after around 2 minutes it shows again a 500 error.

but eventually, the whole site throws a 500 error and I have to reload the php5-fpm service. but when I do that, I have to reset step 5 and start from the beginning.


do you have an idea what the problem could be?

**Comment by quynhvv** [comment]
@bh-ref:
if you have once migrate data in a step and get errors and then you have to click 'Reset' button before re-start the migration on that step.

**Comment by bh-ref** [comment]
@quynhvv I cannot click the 'Reset' button, because the button is not displayed: 

![500 error on step 5](https://cloud.githubusercontent.com/assets/15156912/11751482/0124d58e-a03a-11e5-9366-8258f3215b6f.png)

**Comment by quynhvv** [comment]
Did you fress the F5 key?
If after fress F5 key, the issue still exists and you can't reset this step, you have to re-install the magento2  and re-start the data migration.
Please note that, if you have large data, you should use this tool in local or in a machine with high performance.

**Comment by bh-ref** [comment]
thank you for your fast answer. I did press the F5, but it did not help. I did some changes to the existing .htaccess files in Magento 2, could that be an error cause?

**Comment by quynhvv** [comment]
Yes, maybe that is a root of issue. You should revert the Magento 2 source
to default as a fresh installation.

On Mon, Dec 14, 2015 at 3:53 PM, bh-ref <notifications@github.com> wrote:

> thank you for your fast answer. I did press the F5, but it did not help. I
> did some changes to the existing .htaccess files in Magento 2, could that
> be an error cause?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ubertheme/module-ubdatamigration/issues/1#issuecomment-164381021>
> .
>



-- 

Best regards, Quynh Vu Van.
<http://www.magentocommerce.com/certification/directory/dev/1639183/>
-------------------------------------------
Skype:  quynh.vv
Mobile:  098 525 2002
