### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by dwdonline** [ubertheme/module-ubdatamigration#10]
php -f ./bin/magento setup:di:compile, produces an error:

Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% 2 secs 53.2 MiBPHP Fatal error:  Class 'CComponent' not found in /var/www/html/magento/vendor/ubertheme/module-ubdatamigration/lib/yii/base/CApplicationComponent.php on line 26

**Comment by quynhvv** [comment]
@dwdonline :
To solve that issue let's go to the web root folder of your Magento 2 and run bellow commands:
- `composer require ubertheme/module-ubdatamigration`
- `php -f bin/magento setup:upgrade`
