### ISSUE TITLE
404 Error when clicking on UB Data Migration

### ISSUE THREAD

**Issue by dwdonline** [ubertheme/module-ubdatamigration#11]
site.com/admin/ubdatamigration/index/index/key/... gives and error. 404. See the screenshot. I've re-compiled, redid the static content, cleared the caches, etc.

php 5.6.17, nginx 1.9.9

![screen shot 2016-01-16 at 2 28 55 pm](https://cloud.githubusercontent.com/assets/8183807/12374827/908f686c-bc5d-11e5-8b15-853104a6b9e7.png)

**Comment by williambize** [comment]
Hi @dwdonline ! How did you fix the 404 error with the UberTheme Magento Migration tool? I'm having the same problem.

Thanks!

**Comment by quynhvv** [comment]
Hi williambize,
Thank you working around with this tool. Let's use this tool in Apache server.
Regards,
Mall.

**Comment by williambize** [comment]
I'm using Apache...

**Comment by quynhvv** [comment]
So, let's share me what is the **web root folder ** of your site now?
