### ISSUE TITLE
Error 500 mysqli_connect(): on step 1

### ISSUE THREAD

**Issue by zdravkok** [ubertheme/module-ubdatamigration#13]
After installing the module on Bitnami's Magento 2 ami, I get this error after step 1:

```
Error 500
mysqli_connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known
```

New db was created and privileges set.
I tried using localhost/127.0.0.1 as well as socket connection for host field
Tried with root db user as well.
Magento was upgraded to 2.0.2 beforehand
I did mess around with file/folder permissions after Magento upgrade
Didn't try on localhost

**Comment by zdravkok** [comment]
Works on my localhost Ubuntu desktop, out of the box setup. I am assuming something is problematic with Bitnami stack.

**Comment by quynhvv** [comment]
Hi zdravkok,
Thank you working with this tool.
Seem you are wrong config in your server.
Can you show me more detail about your working? 
What version of PHP in your server?
We have not testing this tool in Magento 2.0.2 but i think it work fine.
Also, please note that:
As data migration itself is a complex task as it relates to different factors including the server condition etc., we do provide migration custom service. Just add a note here, in case you might want to use our service.
https://www.ubertheme.com/magento-custom-services/

Regards,
Mall.

**Comment by zdravkok** [comment]
Hi Mall, 

Thanks for the comment. It works for me too locally, and it worked with Digital Ocean 1click droplet. It doesn't work with Bitnami AWS ami launched as EC2 instance. You can find it here: https://bitnami.com/stack/magento . I assume it's because of their mysql through socket setup. I will probably take this to them if I need it in future, for now I am using Digital Ocean. I will close the issue.

**Comment by quynhvv** [comment]
@zdravkok : Yes, thanks for your working around with this tool.
If you need further assistance, let's contact us at:
https://www.ubertheme.com/magento-custom-services/
Regards,
Mall.
