### ISSUE TITLE
CDbConnection failed to open the DB connection: could not find driver

### ISSUE THREAD

**Issue by comunidademagento** [ubertheme/module-ubdatamigration#14]
Hello,

How to fix this error, please …

![img](https://cloud.githubusercontent.com/assets/7476455/12818588/a43f071a-cb3e-11e5-8c79-c4e5816d4fc6.png)

**Comment by quynhvv** [comment]
@comunidademagento : This tool use the sqlite database. Let's enable the php sqlite to solve the issue as you said.
Regards,
Mall.

**Comment by comunidademagento** [comment]
Hi @quynhvv - Thanks.

Solution is ...

sudo apt-get install sqlite php5-sqlite
service apache2 restart
