### ISSUE TITLE
CDbException

### ISSUE THREAD

**Issue by holozaen** [ubertheme/module-ubdatamigration#2]
Hi. I get a "CDbConnection failed to open the DB connection: could not find driver" on opening the menu item. pdo_mysql installed and working.

**Comment by quynhvv** [comment]
@holozaen: You have to install and enabled the sqlite in your web server.

**Comment by vijayhwg** [comment]
Hi,
https://github.com/ubertheme/module-ubdatamigration/blob/master/README.md

I have upload your module-ubdatamigration in my local system for data migration magento 1.9.1.1 to magento 2.0.
Its working fine till 3 step but Getting error in Step-4 : Migrate Category

Error:
CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicata du champ 'home-1' pour la clef 'URL_REWRITE_REQUEST_PATH_STORE_ID'. The SQL statement executed was: INSERT INTO `url_rewrite` (`redirect_type`, `is_autogenerated`, `entity_type`, `entity_id`, `request_path`, `target_path`, `store_id`, `description`, `metadata`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8) 

Can you please help me?
Thanks
