### ISSUE TITLE
mysqli_connect(): Headers and client library minor version mismatch

### ISSUE THREAD

**Issue by elioermini** [ubertheme/module-ubdatamigration#20]
Hello after clicking start this is the error I'm facing:
`mysqli_connect(): Headers and client library minor version mismatch. Headers:50547 Library:100024
`
The installations of Magento 1.9.2.3 and 2.0.2 are on the same server and use PHP 5.5 and Maria Db 10.

Any idea what can cause this?
Thanks

**Comment by quynhvv** [comment]
@elioermini : Please find sulution here: http://stackoverflow.com/questions/10759334/headers-and-client-library-minor-version-mismatch
Thanks,
Mall.
