### ISSUE TITLE
Error in enabling module

### ISSUE THREAD

**Issue by renatofig** [ubertheme/module-ubdatamigration#21]
When using in WinSCP
php -f magento module:enable --clear-static-content Ubertheme_Ubdatamigration
error
bin/magento must be run as a CLI application

In Putty error is
Magento supports PHP 5.5.0 or later but I'm using php 5.6 in siteground

Can you help ?

**Comment by quynhvv** [comment]
Hi renatofig, 
For technical question please submit here: http://ubertheme.com/questions/
In case you want to use service from ours, let's submit here: http://ubertheme.com/magento-custom-services/
Thanks,
Mall,
