### ISSUE TITLE
404 Not Found after Install

### ISSUE THREAD

**Issue by BtotheT** [ubertheme/module-ubdatamigration#23]
Steps:
 - Clean Mage2 install
 - Install from steps listed UBDataMigration
 - Flush/Refresh all cache - bin/magento cache:clean, bin/magento cache:flush
 - Re-compile bin/magento bin/magento setup:di:compile
 - Rebuild all static resources bin/magento setup:static-content:deploy

404 Error is specifically: The requested URL /pub/ub-tool/ was not found on this server.

Viewing folder structure, that folder does exist, with only one folder within, 
- ub-tool
   - yii

No index or htaccess within ub-tool folder (not sure if that matters but wanted to point it out).

**Comment by quynhvv** [comment]
Hi BtotheT,
For technical question please submit here: http://www.ubertheme.com/questions/
Thanks.
Mall.

**Comment by BtotheT** [comment]
Thanks Mall,

I'll continue from here: https://www.ubertheme.com/question/ub-data-migration-404-error/
