### ISSUE TITLE
CDbException

### ISSUE THREAD

**Issue by vijayhwg** [ubertheme/module-ubdatamigration#3]
Hi,
https://github.com/ubertheme/module-ubdatamigration/blob/master/README.md

I have upload your module-ubdatamigration in my local system for data migration magento 1.9.1.1 to magento 2.0.
Its working fine till 3 step but Getting error in Step-4 : Migrate Category

Error:
CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicata du champ 'home-1' pour la clef 'URL_REWRITE_REQUEST_PATH_STORE_ID'. The SQL statement executed was: INSERT INTO url_rewrite (redirect_type, is_autogenerated, entity_type, entity_id, request_path, target_path, store_id, description, metadata) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8)

pub\ub-tool\yii\db\CDbCommand.php(358)

Can you please help me?
Thanks

**Comment by quynhvv** [comment]
@vijayhwg : 
Seem you have added any categories before use this tool?
Please note that, you have to install a Magento2 fresh (without any data sample) before use this tool to migrate your data.

**Comment by vijayhwg** [comment]
Hi Quynh,

I have installed fresh magento 2 without sample data and then I have not created category, product or anything changes in magento 2 frontend or backend.

I have first installed magento 2 after install module-ubdatamigration using command. I follow same step as you define.

Thanks

**Comment by quynhvv** [comment]
Hi vijayhwg,
Let's make reset the step 4 and re-try data migration in this step and tell me know how it goes.

**Comment by salelsol** [comment]
Hi, I can´t update data of the last three days (new customers registered and new oders recived).

Best Regards
Toni Moya

**Comment by quynhvv** [comment]
@salelsol: If you want to update the latest customers, orders you can re-start the data migration on step 6 and step 7.

**Comment by salelsol** [comment]
- Hi  Quynh Vu Van, I´ve reset many times steps 6 and 7, but not works (not update lasted customer and orders).

Best Regards
Toni Moya

**Comment by balack** [comment]
Hi Quynh Vu Van, I´ve reset many times steps 9, but not works and error 
Error 500
Undefined variable: migrated_tax_ids
Can you help me, pls ? Thank you so much
pic 1: ![yqm2yt5 1](https://cloud.githubusercontent.com/assets/7817777/12109915/5305bb2e-b3b9-11e5-98d6-5f49589ba1db.png)

pic 2: 
![yqsxpxx 1](https://cloud.githubusercontent.com/assets/7817777/12109926/7333f488-b3b9-11e5-999e-0def58d60f1f.png)

**Comment by quynhvv** [comment]
@balack : 
Yes, to solve the issue: http://pasteboard.co/yQsxPxX.png
let open the php file at path: `pub/ub-tool/protected/controllers/MigrateController.php`

and find to the code lines:
```
//variables to log
$migrated_object_ids = array();
$migrated_tax_rule_ids = $migrated_tax_rate_ids = $migrated_catalog_rule_ids = array();
```
and replace it by code lines:
```
//variables to log
$migrated_object_ids = $migrated_tax_ids = array();
$migrated_tax_rule_ids = $migrated_tax_rate_ids = $migrated_catalog_rule_ids = array();
```
and reset the step 9 and restart the data migration on this step.

Do it to solve the issue.

Regards,
quynhvv

**Comment by salelsol** [comment]
- Hi Quyunh, I need help for solve this issue, customer update step 6  works fine but when I´m try ing upfdate orders update step 7 then show up this warning:



Best Regards
Toni Moya

**Comment by salelsol** [comment]
- Hi Quyung, just upgrading to M2.0.3 I ca´t finish compiler process due a this error:

 14% 1 sec 50.0 MiBPHP Fatal error: Class 'CCache' not found in /home/39552-37539.cloudwaysapps.com
/jwzsyzgrdt/public_html/vendor/ubertheme/module-ubdatamigration/lib/yii/caching/CXCache.php on line 22        

Best Regards
Toni

**Comment by quynhvv** [comment]
@salelsol: 
Thank you working around with this tool.
For technical question, let's submit here: http://www.ubertheme.com/questions/
Regards,
Mall.

**Comment by ashokget** [comment]
Hi, in the migration magento 1 to magento 2 got this error

 CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `tax_calculation_rule` (`tax_calculation_rule_id`, `code`, `priority`, `position`, `calculate_subtotal`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4)
using Migrate Data Tool of uberthme

plz help me out this is just final step 9

**Comment by UberthemeTeam** [comment]
Hi @ashokget ,

You can delete the record with primary key id=1 in the tax_calculation_rule table to solve that  issue. 

However, the script on our Github was based on an outdated code base which might lead to unexpected issues. We highly recommend you consider to move forward with our newer module version [here](https://www.ubertheme.com/magento-extensions-2-x/magento-2-data-migration-pro/). 

Regards,
Ubertheme team
