### ISSUE TITLE
Can't compile di, Class >'CDbSchema' not found in 

### ISSUE THREAD

**Issue by swayoleg** [ubertheme/module-ubdatamigration#38]
`php bin/magento setup:di:compile `

> Compilation was started.
> Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 54.0 MiBPHP Fatal error:  Class >'CDbSchema' not found in /app/app/code/Ubertheme/Ubdatamigration/lib/yii/db/schema/oci/COciSchema.php on line 19

Magento CE 2.1.4
Ubertheme_Ubdatamigration   1.0.6 Lite version

**Comment by UberthemeTeam** [comment]
Hi Swayoleg,

We wonder you referred to our [UB Data Migration Lite v1.0.6](https://www.ubertheme.com/magento-extensions-2-x/magento-2-data-migration-tool/) on our site, or the old version here at Github? 

The old version on Github is no longer maintained, and replaced with a newer [Pro version](https://www.ubertheme.com/magento-extensions-2-x/magento-2-data-migration-pro/). 

Meanwhile, the Lite v1.0.6 is available for Magento 2.0.7 only. This version is mainly for testing purpose, and comes with some limitations: 
- Magento must be a fresh installation
- It does not not support NGINX
- Provide limited features, compared with Pro version

Thanks for your understanding. 

Regards,
Ubertheme team

**Comment by swayoleg** [comment]
Ok so please close the issue

**Comment by UberthemeTeam** [comment]
Hi Swayoleg,
In case you have additional question, please submit a ticket via our [helpdesk](https://www.ubertheme.com/questions/), we will check and get back to you.

Regards,
Ubertheme team
