### ISSUE TITLE
Missing permissions mkdir

### ISSUE THREAD

**Issue by cod3gen** [ubertheme/module-ubdatamigration#4]
Hello!

I have come across following problem: 

a:4:{i:0;s:128:"Warning: mkdir(): Permission denied in /var/www/html/magento2/vendor/ubertheme/module-ubdatamigration/Helper/File.php on line 33";i:1;s:7188:"#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'mkdir(): Permis...', '/var/www/html/m...', 33, Array)
#1 /var/www/html/magento2/vendor/ubertheme/module-ubdatamigration/Helper/File.php(33): mkdir('/var/www/html/m...', 509)
#2 /var/www/html/magento2/vendor/ubertheme/module-ubdatamigration/Controller/Adminhtml/Index/Index.php(48): Ubertheme\Ubdatamigration\Helper\File::xcopy('/var/www/html/m...', '/var/www/html/m...', 509)
#3 /var/www/html/magento2/var/generation/Ubertheme/Ubdatamigration/Controller/Adminhtml/Index/Index/Interceptor.php(25): Ubertheme\Ubdatamigration\Controller\Adminhtml\Index\Index->execute()
#4 /var/www/html/magento2/lib/internal/Magento/Framework/App/Action/Action.php(102): Ubertheme\Ubdatamigration\Controller\Adminhtml\Index\Index\Interceptor->execute()
#5 /var/www/html/magento2/app/code/Magento/Backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#6 [internal function]: Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#7 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#8 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Ubertheme\Ubdatamigration\Controller\Adminhtml\Index\Index\Interceptor->___callParent('dispatch', Array)
#9 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Ubertheme\\Ubdat...', 'dispatch', Object(Ubertheme\Ubdatamigration\Controller\Adminhtml\Index\Index\Interceptor), Array, 'adminAuthentica...')
#10 /var/www/html/magento2/app/code/Magento/Backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#11 [internal function]: Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Ubertheme\Ubdatamigration\Controller\Adminhtml\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#12 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#13 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Ubertheme\\Ubdat...', 'dispatch', Object(Ubertheme\Ubdatamigration\Controller\Adminhtml\Index\Index\Interceptor), Array, 'designLoader')
#14 /var/www/html/magento2/lib/internal/Magento/Framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#15 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Ubertheme\Ubdatamigration\Controller\Adminhtml\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#16 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#17 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Ubertheme\\Ubdat...', 'dispatch', Object(Ubertheme\Ubdatamigration\Controller\Adminhtml\Index\Index\Interceptor), Array, 'adminMassaction...')
#18 /var/www/html/magento2/app/code/Magento/Backend/App/Action/Plugin/MassactionKey.php(33): Ubertheme\Ubdatamigration\Controller\Adminhtml\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#19 [internal function]: Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Ubertheme\Ubdatamigration\Controller\Adminhtml\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#20 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#21 /var/www/html/magento2/var/generation/Ubertheme/Ubdatamigration/Controller/Adminhtml/Index/Index/Interceptor.php(53): Ubertheme\Ubdatamigration\Controller\Adminhtml\Index\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#22 /var/www/html/magento2/lib/internal/Magento/Framework/App/FrontController.php(55): Ubertheme\Ubdatamigration\Controller\Adminhtml\Index\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#23 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#24 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#25 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#26 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#27 /var/www/html/magento2/lib/internal/Magento/Framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#28 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#30 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'storeCookieVali...')
#31 /var/www/html/magento2/app/code/Magento/Store/Model/Plugin/StoreCookie.php(78): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#32 [internal function]: Magento\Store\Model\Plugin\StoreCookie->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#33 /var/www/html/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#34 /var/www/html/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#35 /var/www/html/magento2/lib/internal/Magento/Framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#36 /var/www/html/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#37 /var/www/html/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#38 {main}";s:3:"url";s:113:"/magento2/admin/ubdatamigration/index/index/key/4e06061fab34eef491816417bcdd7b559bc375571c003183be71b0edd8d109d7/";s:11:"script_name";s:19:"/magento2/index.php";}

It seems to be missing some permissions, but there is no such problems with other than this extension it seems.

Any ideas?

Thanks,
Stian

**Comment by quynhvv** [comment]
@cod3gen: To solve the issue, let's make write permission for **/pub** folder in your Magento 2 website.
and fress F5 key to continue.

**Comment by cod3gen** [comment]
Hello @quynhvv 

Thanks for your reply. /pub folder in Magento 2 root folder already have 777 permissions...

Stian

**Comment by gitpramos** [comment]
Run dev permissions 
find . -type d -exec chmod 770 {} \; && find . -type f -exec chmod 660 {} \; && chmod u+x bin/magento
