### ISSUE TITLE
 unserialize() error

### ISSUE THREAD

**Issue by Robx64** [ubertheme/module-ubdatamigration#41]
Guys is it work with Magento 2.2.0 yet?
Getting error right after open the page.

Notice: unserialize(): Unexpected end of serialized data in /home/localdev/public_html/migra/yii/caching/CCache.php on line 108

Notice: unserialize(): Error at offset 0 of 1 bytes in /home/localdev/public_html/migra/yii/caching/CCache.php on line 108

**Comment by UberthemeTeam** [comment]
Hi @Robx64 , 

Yes, our latest [UB Data Migration Pro](https://www.ubertheme.com/magento-extensions-2-x/magento-2-data-migration-pro/) version 3.1.1 is fully compatible with Magento 2.2.0. 

It's true that Magento 2.2.0 changed the method from serialized() to json_encode(). Our latest Pro ver3.1.1 already comes with tweak code to handle this change automatically. 

Hope that helps. 

**PS.** Please note that the old script here at Github is no longer maintained, and has been replaced with UB Data Migration Pro. 

Regards,
Ubertheme team

**Comment by Robx64** [comment]
Thank you
