### ISSUE TITLE
Php version

### ISSUE THREAD

**Issue by emilshamloo** [ubertheme/module-ubdatamigration#5]
Magento 1.9.X is working with PHP 5.5, but Mangeto2 is working with PHP 5.6!
How can I have different php's in the same server?﻿
Regards
Emil

**Comment by quynhvv** [comment]
@emilshamloo 
Please follow this: http://devdocs.magento.com/guides/v2.0/install-gde/system-requirements.html
Regards,
quynhvv

**Comment by emilshamloo** [comment]
Hi, and thanks for your reply.
I red that. It is talking about the issue with the time zone, but when I install Magento2 in the Php 5.5, then none of the Css or jsc working.
Thanks.

**Comment by quynhvv** [comment]
@emilshamloo 
The issue come from folder/files permission was not matched or the performance of your web server can't deploy needed static files at installation runtime.
you can deploy the static files by command line:

`php bin/magento setup:static-content:deploy`

Regards,
quynhvv

**Comment by emilshamloo** [comment]
Hi, and thanks for your help.
I have installed my new magento installation to a subdomain called 
www.fresh.supermarket.no
and the new installation files are in public_html/fresh.
Is this correct command then?
|php bin/fresh setup:static-content:deploy|
|Because when I try your command, I get this "Could not open input file: 
bin/magento"
| Regards
Emil

Den 07.01.2016 10:51, skrev Quynh Vu Van:

**Comment by quynhvv** [comment]
@emilshamloo : 
To solve the issue, let's enable write permission for file at: bin/magento 
Regards,
quynhvv

**Comment by emilshamloo** [comment]
Hi,
I've changed the permission like this, but still not working
Regards
Emil


Med vennligst hilsen
Emil Shamloo
Daglig leder
Tel: 99864260
http://supermarket.no <http://www.supermarket.no>

Den 11.01.2016 02:26, skrev Quynh Vu Van:

**Comment by quynhvv** [comment]
@emilshamloo 
>I've changed the permission like this, but still not working

How did you change the permission of the file at bin/magento ?

Regards,
Mall.
