### ISSUE TITLE
Get a 500 error after install

### ISSUE THREAD

**Issue by npearson72** [ubertheme/module-ubdatamigration#6]
I followed your directions, but after I install I get a 500 error.

After I run: 

```
$ php -f ./bin/magento setup:upgrade
```

I get:

```
Cache cleared successfully
File system cleanup:
/var/www/html/magento/var/generation/Composer
/var/www/html/magento/var/generation/Magento
/var/www/html/magento/var/generation/Symfony
The directory '/var/www/html/magento/var/di/' doesn't exist - skipping cleanup
Updating modules:
Schema creation/updates:
Module 'Magento_Store':
Module 'Magento_AdvancedPricingImportExport':
...
Please re-run Magento compile command
```

At this point I can't access the site and am getting a 500 error.

I then tried running:

```
$ magento setup:di:compile
```

And I get:

```
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14%
3 secs 43.0 MiBPHP Fatal error:  Class 'CComponent' not found in /var/www/html/magento/vendor/ubertheme/module-ubdatamigration/lib/yii/base/CApplicationComponent.php on line 26
```

**Comment by quynhvv** [comment]
@npearson72 :

>I followed your directions, but after I install I get a 500 error.

=> Let's enable the developer mode by commands:

`php -f PATH_TO_YOUR_MAGENTO2/bin/magento deploy:mode:set developer`

and provide me detail information of the errors.

Regards,
Quynhvv

**Comment by quynhvv** [comment]
@npearson72
Let's update the latest version of this tool to solve the issue as you said.
Regards,
Mall.
