### ISSUE TITLE
Fatal error: running bin/magento setup:di:compile

### ISSUE THREAD

**Issue by gitpramos** [ubertheme/module-ubdatamigration#8]
After running bin/magento setup:upgrade, runned bin/magento setup:di:compile

Fatal error: running bin/magento setup:di:compile
--------->
Repositories code generation... 1/7 [====>-----------------------]  14% 2 secs 54.0 MiBPHP Fatal error:  Class 'Mage2CatalogProductOptionTypePricePeer' not found in /var/www/clients/client2/web2/web/byvisor/vendor/ubertheme/module-ubdatamigration/lib/protected/models/mage2/Mage2CatalogProductOptionTypePrice.php on line 4

**Comment by quynhvv** [comment]
@gitpramos 
To solve that issue, go to web root folder of your Magento 2 and run bellow commands:
- `composer require ubertheme/module-ubdatamigration`
- `php -f bin/magento setup:upgrade`
