### ISSUE TITLE
404 Backend Error when viewing UB Data Migration Tab in backend

### ISSUE THREAD

**Issue by andidhouse** [ubertheme/module-ubdatamigration#9]
We get a 404 error when viewing the UB Data Migration Tab in backend. Not the hole site but after the headline "UB Data Migration".

Maybe this is related to the nginx standard configuration file located in the magneto root and showing:

----------------
location /pub {
    location ~ ^/pub/media/(downloadable|customer|import|theme_customization/.*\.xml) {
        deny all;
    }
    alias $MAGE_ROOT/pub;
    add_header X-Frame-Options "SAMEORIGIN";
}
----------------
I think its not possible here to run the index.php file or am i wrong?

Thanks!

**Comment by andidhouse** [comment]
when compiling after installation:

Please re-run Magento compile command
root@euve103495:/var/www/html/magento2# php -f /var/www/html/magento2/bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% 5 secs 52.8 MiBPHP Fatal error:  Class 'Yii' not found in /var/www/html/magento2/vendor/ubertheme/module-ubdatamigration/lib/protected/components/UserMenu.php on line 3

:-1:

**Comment by balack** [comment]
I have error same http://pasteboard.co/PDYLyBC.png

**Comment by quynhvv** [comment]
Hi Guys,
To solve that issue, go to web root folder of your Magento 2 and run bellow commands:
composer require ubertheme/module-ubdatamigration
php -f bin/magento setup:upgrade

**Comment by andidhouse** [comment]
nope at all. this command are to install the extension like posted in the description... 

what about the compile error? hole magento is stuck after installing.... not good.

**Comment by dwdonline** [comment]
That fixed it for me (it gets the newer version).

**Comment by andidhouse** [comment]
the commands solve the compile issues - but not the 404 in the backend of the data migration tab. Are you shure this is nginx compatible?

**Comment by balack** [comment]
I'm run again

composer require ubertheme/module-ubdatamigration
php -f bin/magento setup:upgrade

But error not fix :(

**Comment by quynhvv** [comment]
@andidhouse:
Sorry, we haven't test this tool in Nginx server.
That issue seem related to .htaccess file in web root folder of this too at
`/pub/ub-tool/.htaccess` => this for URL Rewrite
You should find solution to handle this in Nginx settings.

**Comment by quynhvv** [comment]
@balack : What issues you get now? Can you show me more information about your working?

**Comment by balack** [comment]
Step 1 : 404 page error - http://pasteboard.co/SpoEVcW.png

step 2: Run  composer require ubertheme/module-ubdatamigration
http://pasteboard.co/SvXk4Zo.png

Step3: run php -f bin/magento setup:upgrade
http://pasteboard.co/Sw3Obx2.png

Step 4: Return admin page and...http://pasteboard.co/Swg2asA.png :(

**Comment by dwdonline** [comment]
It gives 404 with Nginx, but when I switch to Apache, it works. 

I'm using this Nginx configuration https://github.com/magenx/Magento-nginx-config/tree/master/magento2

**Comment by andidhouse** [comment]
Hi quynhvv,

no .htaccess files are not relevant in nginx configuration. 

The problem is that it is not the sense of magento handling to tweak server configuration for each module. 

A simple way to solve this (and maybe also the best way) is to return to a php script like in the older version. I also see absolutely no sense in installing a migration module that is used once to import as a module in extension in case to hold magento clean and working. 

Is it possible to copy the files to a folder and run the script via url like the older version?

**Comment by quynhvv** [comment]
@andidhouse

After install this tool via composer, you can use bellow URL to access this tool in front-end:
`http://YOUR_MAGENTO2_URL/pub/ub-tool/`

Let's try use it and tell me know how it goes.
Regards,
quynhvv

**Comment by bpoiss** [comment]
I have the same problem. I tried to navigate to http://YOUR_MAGENTO2_URL/pub/ub-tool/ as you mentioned, because I don't see a reason to place this in magento2 backend anyway because I only want to do this a single time. First problems I ran into were that nginx denys the acces. I reconfigured my whole nginx configuration and changed the webroot from mage_root_dir/pub to mage_root dir. Now when I request the URL http://YOUR_MAGENTO2_URL/pub/ub-tool/ it redirects to http://YOUR_MAGENTO2_URL/pub/ub-tool/index.php/migrate/step1 and I get 404 not found again. Any solution for this problem?

**Comment by quynhvv** [comment]
@bpoiss: 
Let's use this tool with Apache at this time ;)

**Comment by antuz88** [comment]
Hi,
have you rebuild permission to files?

**Comment by quynhvv** [comment]
@antuz88 
Let go to web root folder of your Magento 2 and run bellow commands:
composer require ubertheme/module-ubdatamigration
php -f bin/magento setup:upgrade

Regards,
Mall.

**Comment by redboxmarcins** [comment]
@dwdonline  I think I found solution for that
Add that to magento 2 nginx.conf file 

```
location /ub-tool {
        try_files $uri $uri/ @rewrite;
}

location @rewrite {
    rewrite ^ /ub-tool/index.php;
}
```

also there must be a hotfix done in vendor/ubertheme/module-ubdatamigration/Block/Index.php
```
public function getToolUrl(){
        $pubFolder = \Magento\Framework\App\Filesystem\DirectoryList::PUB;
        $toolUrl = $this->_storeManager->getStore()->getBaseUrl().'/ub-tool';
        $toolUrl = str_replace('index.php/', '', $toolUrl);
        return $toolUrl;
}
```

**Comment by williambize** [comment]
Hi @dwdonline! I'm not sure if your fix to the 404 error when trying to access the UberTheme Magento Migration Tool also fixes the same issue on Apache. Is this fix for nginx or for Apache as well? I'm running Apache and having the same issue of hitting 4o4 Error whenever I tried to access Uber Migration Tool.

Thank you!

**Comment by quynhvv** [comment]
Hi williambize,
Thank you working around with this tool. For technical question please submit here: http://www.ubertheme.com/questions/
Regards,
Mall.

**Comment by jeversen** [comment]
Hi @quynhvv I'm trying to install with magento 2.1.4 but it won't install. When I'm trying to install through composer it fails on me, any ideas:

```
magento@web2:/var/www/magento2$ composer require ubertheme/module-ubdatamigration
Using version ^1.0 for ubertheme/module-ubdatamigration
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - ubertheme/module-ubdatamigration v1.0.0 requires magento/module-backend 100.0.* -> satisfiable by magento/module-backend[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9].
    - ubertheme/module-ubdatamigration v1.0.1 requires magento/module-backend 100.0.* -> satisfiable by magento/module-backend[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9].
    - ubertheme/module-ubdatamigration v1.0.2 requires magento/module-backend 100.0.* -> satisfiable by magento/module-backend[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9].
    - ubertheme/module-ubdatamigration v1.0.3 requires magento/module-backend 100.0.* -> satisfiable by magento/module-backend[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9].
    - ubertheme/module-ubdatamigration v1.0.4 requires magento/module-backend 100.0.* -> satisfiable by magento/module-backend[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9].
    - magento/module-backend 100.0.2 requires magento/module-store 100.0.* -> satisfiable by magento/module-store[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6].
    - magento/module-backend 100.0.3 requires magento/module-store 100.0.* -> satisfiable by magento/module-store[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6].
    - magento/module-backend 100.0.4 requires magento/module-store 100.0.* -> satisfiable by magento/module-store[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6].
    - magento/module-backend 100.0.5 requires magento/module-store 100.0.* -> satisfiable by magento/module-store[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6].
    - magento/module-backend 100.0.6 requires magento/module-store 100.0.* -> satisfiable by magento/module-store[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6].
    - magento/module-backend 100.0.7 requires magento/module-store 100.0.* -> satisfiable by magento/module-store[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6].
    - magento/module-backend 100.0.8 requires magento/module-store 100.0.* -> satisfiable by magento/module-store[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6].
    - magento/module-backend 100.0.9 requires magento/module-store 100.0.* -> satisfiable by magento/module-store[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6].
    - magento/module-backend 100.0.2 requires magento/module-store 100.0.* -> satisfiable by magento/module-store[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6].
    - magento/module-backend 100.0.3 requires magento/module-store 100.0.* -> satisfiable by magento/module-store[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6].
    - magento/module-backend 100.0.4 requires magento/module-store 100.0.* -> satisfiable by magento/module-store[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6].
    - magento/module-backend 100.0.5 requires magento/module-store 100.0.* -> satisfiable by magento/module-store[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6].
    - magento/module-backend 100.0.6 requires magento/module-store 100.0.* -> satisfiable by magento/module-store[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6].
    - magento/module-backend 100.0.7 requires magento/module-store 100.0.* -> satisfiable by magento/module-store[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6].
    - magento/module-backend 100.0.8 requires magento/module-store 100.0.* -> satisfiable by magento/module-store[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6].
    - magento/module-backend 100.0.9 requires magento/module-store 100.0.* -> satisfiable by magento/module-store[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6].
    - magento/module-store 100.0.6 requires magento/module-media-storage 100.0.* -> no matching package found.
    - magento/module-store 100.0.5 requires magento/module-media-storage 100.0.* -> no matching package found.
    - magento/module-store 100.0.4 requires magento/module-media-storage 100.0.* -> no matching package found.
    - magento/module-store 100.0.3 requires magento/module-media-storage 100.0.* -> no matching package found.
    - magento/module-store 100.0.2 requires magento/module-media-storage 100.0.* -> no matching package found.
    - magento/module-store 100.0.6 requires magento/module-media-storage 100.0.* -> no matching package found.
    - magento/module-store 100.0.5 requires magento/module-media-storage 100.0.* -> no matching package found.
    - magento/module-store 100.0.4 requires magento/module-media-storage 100.0.* -> no matching package found.
    - magento/module-store 100.0.3 requires magento/module-media-storage 100.0.* -> no matching package found.
    - magento/module-store 100.0.2 requires magento/module-media-storage 100.0.* -> no matching package found.
    - Installation request for ubertheme/module-ubdatamigration ^1.0 -> satisfiable by ubertheme/module-ubdatamigration[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

**Comment by UberthemeTeam** [comment]
Hi @jeversen ,

It's pity that we no longer maintain our old script distributed here on Github. We replace with a newer version - UB Data Migration Pro https://www.ubertheme.com/magento2/ub-data-migration-pro-v3/

Please consider to move forward with this new version, a complete overhaul with brand new features like Delta migration, CLI support, plus various bug fixes and optimization. This version is fully compatible with Magento 2.1.4. 

Regards,
Ubertheme team

**Comment by jeversen** [comment]
Hi @UberthemeTeam 

Is there also a 'lite' version of this 3.0 version ? Would like to test if it works first. Or are there only paid versions which work with magento 2.1.4 now ?

best regards

**Comment by UberthemeTeam** [comment]
Hi @jeversen 

We have [a lite version](https://www.ubertheme.com/magento-extensions-2-x/magento-2-data-migration-tool/), but it is still based on the old codebase and available for Magento 2.0.7 only. 

As the difference between the Lite vs. our Pro version is huge, as indicated in this [comparison matrix](https://www.ubertheme.com/magento2/ub-data-migration-pro-v3/), we do recommend you consider Pro to save time (you can make a test with the Lite version on Magento 2.0.7 though). 

Regards,
Ubertheme team

**Comment by anamikaupadhyay** [comment]
Hello Guys,

I am using data migration tool lite in magento 2.0.7 but its showing 404 page error. I am using apache. can you please help me to fix this issue?

Thanks!

**Comment by UberthemeTeam** [comment]
Hi @anamikaupadhyay, 

If you use our UB Data Migration Lite [here](https://www.ubertheme.com/magento-extensions-2-x/magento-2-data-migration-tool), please submit a ticket via our forum [helpdesk](https://www.ubertheme.com/ask-question/), so that we can provide you better help. 

Anyway, due to our limited resources, we could not provide updates to the Lite version, thus it still uses an outdated codebase, with limited features. 

Regards,
Ubertheme team
